name: Nuestra primera pipeline

on:
  push:
    branches:
      - main
      - dev
      - feature/x

jobs:
  builds:
    runs-on: windows-2019

    steps:
        #- name: fetch last commit
        #  uses: actions/checkout@v4
        #  with:
        #    fetch-depth: 0

        - name: checkout repository
          uses: actions(checkout@v2

        #Confifurar jdk 11
        - name: configuree JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: '11'

        #Compilar el proyecto
        - name: build with maven
          run: mvn clean install

        #Ejecutamos TEST
        - name: run tests
          run: mvn tests

        #save artifact
        - name: save artifact
          uses: actions/download-artifact@v2
          with:
            name: Perseo
            path: target/*.jar
